LIBASPACE-333. Workaround for gem version error on startup
Modifies the "public_suffix" and "addressable" gem versions in the
"aspace-oauth/Gemfile.lock" file to prevent the following error at
startup:

```
Dec 05, 2022 8:23:43 PM org.eclipse.jetty.server.handler.ContextHandler$Context log
WARNING: ERROR: initialization failed
org.jruby.rack.RackInitializationException: Could not find public_suffix-4.0.6 in any of the sources
from /apps/aspace/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize'
from org/jruby/RubyArray.java:2621:in `map!'
from /apps/aspace/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
from /apps/aspace/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
...
```

It is unclear what is causing this error, and this change can be only
considered as a workaround, not an actual fix. It was suggested on
the ArchivesSpace Users Group list, see

http://lyralists.lyrasis.org/pipermail/archivesspace_users_group/2022-December/009710.html

https://issues.umd.edu/browse/LIBASPACE-333